default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: taskello_development

test:
  <<: *default
  database: taskello_test

production:
  <<: *default
  database: taskello_production
  username: taskello
  password: <%= ENV["TASKELLO_DATABASE_PASSWORD"] %>
